name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./my-portfolio
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run sitemap script
        working-directory: ./my-portfolio
        run: node sitemap.cjs 

      - name: Commit and Push sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap.xml [skip ci]"
          file_pattern: 'my-portfolio/public/sitemap.xml'